version: '3.1'

services:

  db:
    image: postgres:16.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  pgadmin:
    image: dpage/pgadmin4:7.8
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
    volumes:
      - ./backend/servers.json:/pgadmin4/servers.json

  maildev:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
      - "1025:1025"