version: '3.1'

services:

  db:
    container_name: PostgreSQL
    image: postgres:16.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:7.8
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: root
    restart: always
    volumes:
      - ./backend/servers.json:/pgadmin4/servers.json

  maildev:
    container_name: MailDev
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
      - "1025:1025"

  react:
    container_name: React
    build:
      dockerfile: ../docker/frontend/Dockerfile
    volumes:
      - ../para-front:/usr/src/app/
    ports:
      - "3000:3000"
    environment:
      - WDS_SOCKET_HOST=127.0.0.1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run start